# 4. tensor的统计运算

### 常见运算函数(搞清楚维度就可以)
1) sum()求和
2) mean()求均值
3) max()/min()求最大/最小值及其索引
4) argmax()/argmin()求最大值/最小值的索引
5) std()求标准差
6) unique()去重
7) sort()排序


In [45]:
import torch
import numpy as np

In [ ]:
# sum
tensor1 = torch.randint(1, 10, (3, 2, 4))
print(tensor1)
print(tensor1.sum(dim=2))

In [ ]:
# mean
tensor1 = tensor1.float()
print(tensor1)
print(tensor1.mean())
 
print(tensor1.mean(dim=0))
print(tensor1.mean(dim=1))
print(tensor1.mean(dim=2))

In [53]:
# max / min
print(tensor1)
print(tensor1.max())
print(tensor1.max(dim=2))
print(tensor1.argmax(dim=2))

tensor([[[3., 7., 8., 4.],
         [1., 1., 2., 8.]],

        [[6., 5., 5., 6.],
         [6., 8., 3., 1.]],

        [[3., 6., 7., 5.],
         [5., 8., 9., 6.]]])
tensor(9.)
torch.return_types.max(
values=tensor([[8., 8.],
        [6., 8.],
        [7., 9.]]),
indices=tensor([[2, 3],
        [0, 1],
        [2, 2]]))
tensor([[2, 3],
        [0, 1],
        [2, 2]])


In [66]:
# sort 默认按最后一个维度排序
print(tensor1.sort(dim=0))
# print(tensor1.sort(dim=1))
 # print(tensor1.sort(dim=2))

torch.return_types.sort(
values=tensor([[[3., 5., 5., 4.],
         [1., 1., 2., 1.]],

        [[3., 6., 7., 5.],
         [5., 8., 3., 6.]],

        [[6., 7., 8., 6.],
         [6., 8., 9., 8.]]]),
indices=tensor([[[0, 1, 1, 0],
         [0, 0, 0, 1]],

        [[2, 2, 2, 2],
         [2, 1, 1, 2]],

        [[1, 0, 0, 1],
         [1, 2, 2, 0]]]))


In [90]:
# unique() 去重的维度比较难看，所以一般不需要传维度
print(tensor1.unique())
# print(tensor1.unique(dim=0))
print(tensor1.unique(sorted=False))

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
