# 5. Tensor的一些索引操作

In [ ]:
import torch
import numpy as np

In [35]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
tensor1

tensor([[[8, 1, 6, 1],
         [4, 9, 5, 5],
         [5, 7, 3, 2],
         [9, 7, 2, 1],
         [4, 1, 7, 3]],

        [[9, 4, 1, 5],
         [1, 3, 5, 1],
         [8, 6, 9, 2],
         [5, 5, 1, 5],
         [9, 6, 6, 4]],

        [[2, 4, 4, 2],
         [6, 6, 8, 1],
         [9, 8, 5, 4],
         [7, 7, 1, 7],
         [9, 1, 1, 3]]])

In [34]:
import random
# 1. 简单索引  直接给坐标
print(tensor1[1, 2, 3])


tensor(9)


In [ ]:
# 2. 范围索引 以三维张量举例,其他维度一样 t[st:ed:step, st:ed:step, st:ed:step]
# tensor要求步长必须大于0, 而numpy则没有限制
print(tensor1[:, :, 0:2])
print(tensor1[0, ::2, :]) 

In [37]:
# 3. 花式索引

# 列表索引
print(tensor1[[0, 1, 2], [1, 2, 3], [1, 2, 3]])
print(tensor1[[0, 1, 2], [0, 1, 2]])


tensor([9, 9, 7])
tensor([[8, 1, 6, 1],
        [1, 3, 5, 1],
        [9, 8, 5, 4]])


In [39]:
# 列表的嵌套 : 不嵌套是一对一, 嵌套就是 一对多
print(tensor1[[[0], [1]], [1, 2]])

tensor([[[4, 9, 5, 5],
         [5, 7, 3, 2]],

        [[1, 3, 5, 1],
         [8, 6, 9, 2]]])


In [57]:
# 布尔索引 : 用条件判断表达式,生成一个高维布尔数组,再把这个高维布尔数组作为索引,返回满足条件的元素
# 1.条件映射：将条件表达式应用于数组，生成与原数组形状相同的布尔数组
# 2.元素筛选：根据布尔数组中 True/False 值，选择性地提取原数组中对应位置为 True 的元素
# 3.降维操作：返回的结果是一维数组，包含所有满足条件的元素

# 选取符合条件的某些行或者列:比如说首元素大于5
mask = tensor1[:, :, 0] > 5
print(tensor1[mask])

# 选择所有列的首元素小于3的列
mask = tensor1[:,0,:] < 3 # 当前mask是(3, 4), 而tensor1是(3, 5, 4),所以不能直接应用

# 先把 tensor1 转秩为 (3, 4, 5), 然后再应用

tensor2 = tensor1.mT
print(tensor2[mask].mT)

tensor([[8, 1, 6, 1],
        [9, 7, 2, 1],
        [9, 4, 1, 5],
        [8, 6, 9, 2],
        [9, 6, 6, 4],
        [6, 6, 8, 1],
        [9, 8, 5, 4],
        [7, 7, 1, 7],
        [9, 1, 1, 3]])
tensor([[1, 1, 1, 2, 2],
        [9, 5, 5, 6, 1],
        [7, 2, 9, 9, 4],
        [7, 1, 1, 7, 7],
        [1, 3, 6, 9, 3]])


In [58]:
# 张量转秩常用的方法, 转秩操作返回新的张量视图，不改变原始张量数据
# tensor.transpose(dim0, dim1)  交换两个指定维度
# tensor.permute(dim1, dim2, dim3, ...) 重新排列维度
# x.mT 如果只想对矩阵转秩, 使用x.mT即可

In [61]:
# 选取符合条件的矩阵
# 比如当前要选择的矩阵是(1, 2) > 5
mask = tensor1[:, 1, 2] > 5
print(mask)
print(tensor1[mask])

tensor([False, False,  True])
tensor([[[2, 4, 4, 2],
         [6, 6, 8, 1],
         [9, 8, 5, 4],
         [7, 7, 1, 7],
         [9, 1, 1, 3]]])


In [62]:
mask = tensor1 > 5
print(tensor1[mask])

tensor([8, 6, 9, 7, 9, 7, 7, 9, 8, 6, 9, 9, 6, 6, 6, 6, 8, 9, 8, 7, 7, 7, 9])
