In [24]:
import torch

In [25]:
# 定义数据
x = torch.tensor([[1.0]], requires_grad=True)
y_true = torch.tensor([[2.0]])

In [26]:
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

z = x * w + b
print(z)

tensor([[2.0581]], grad_fn=<AddBackward0>)


In [27]:
loss = torch.nn.MSELoss()

loss_value = loss(z, y_true)
print(loss_value)

tensor(0.0034, grad_fn=<MseLossBackward0>)


In [28]:
# 反向传播
loss_value.backward()

In [29]:
print(w.grad)
print(b.grad)

tensor([[0.1162]])
tensor([0.1162])


In [30]:
print(x.is_leaf)
print(y_true.is_leaf)
print(z.is_leaf)
print(loss_value.is_leaf)

True
True
False
False


In [31]:
# 当我们需要对计算图中的某些张量进行独立处理，同时又不希望影响原有计算图结构时，可以采用以下几种解决方案：
x = torch.rand(2, 2, requires_grad=True)
y = x.detach()
print(x)
print(y)
z = x.mean()
print(z)

tensor([[0.3977, 0.4124],
        [0.2795, 0.5688]], requires_grad=True)
tensor([[0.3977, 0.4124],
        [0.2795, 0.5688]])
tensor(0.4146, grad_fn=<MeanBackward0>)


In [32]:
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())   

5018035950848
5018035950848


In [33]:
x.requires_grad

True

In [36]:
y.fill_(1)
print(y)
print(y.storage())

tensor([[1., 1.],
        [1., 1.]])
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]


In [67]:
x = torch.ones(2, 2, requires_grad=True)
y = x * x
print(x)
print(y)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [68]:
# 分离y
u = y.detach()
u

tensor([[1., 1.],
        [1., 1.]])

In [69]:
z = u * x   

In [70]:
# 反向传播
z.sum().backward()

In [74]:
print(x.grad)
print(x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])
