In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r'../datasets/sgg-data/train.csv')
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
np.random.choice(10, 5)

array([7, 5, 7, 1, 9], dtype=int32)

In [4]:
# 布尔索引
a = np.array([1,2,3,4,5])
case = np.array([True, False, True, False, True])
print(a[case])

[1 3 5]


In [9]:
b = np.arange(0, 10)
b[b>3] = 0
b

array([0, 1, 2, 3, 0, 0, 0, 0, 0, 0])

In [15]:
# arr.reshape的测试，发现传入数组时，解不解包都可以
arr = np.random.randn(3,3,3)
origin_shape = arr.shape
arr = arr.reshape(3, -1)
arr = arr.reshape(*origin_shape) # 等价于arr = arr.reshape(origin_shape)
arr.shape

(3, 3, 3)

In [14]:
# 索引转独热编码测试
# 第一种方式，先创建一个全零矩阵，然后把索引位置的元素设置为1
y = np.array([3, 2, 1, 0, 4, 4, 5, 6, 1])
y_onehot = np.zeros((len(y), 10))
y_onehot[np.arange(len(y)), y] = 1

# 第二种方式，直接从对角矩阵生成(还是花式索引，或者叫高级索引)
y_onehot_1 = np.eye(10)
y_onehot_1[y]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])