In [38]:
import torch
import torch.nn as nn

In [39]:
class MyModel(nn.Module):
    
    def __init__(self):
        super().__init__()
        # 定义网络结构
        self.linear1 = nn.Linear(3, 4)
        self.linear2 = nn.Linear(4, 4)
        self.linear3 = nn.Linear(4, 2)

        # 初始化网络参数
        nn.init.xavier_normal_(self.linear1.weight)
        nn.init.kaiming_normal_(self.linear2.weight)
    

    def forward(self, x):
        z1 = torch.tanh(self.linear1(x))
        z2 = torch.relu(self.linear2(z1))
        return torch.softmax(self.linear3(z2), dim=1)
    
    


In [40]:
net = MyModel()
x = torch.randn(10, 3)
out = net(x)
print(out.data)

tensor([[0.4105, 0.5895],
        [0.4946, 0.5054],
        [0.4762, 0.5238],
        [0.4992, 0.5008],
        [0.3350, 0.6650],
        [0.4955, 0.5045],
        [0.2533, 0.7467],
        [0.5025, 0.4975],
        [0.4955, 0.5045],
        [0.5176, 0.4824]])


In [41]:
# 查看模型参数
# 最简单的方法 直接从对应的层中查看
print(net.linear1.weight)

Parameter containing:
tensor([[-0.6768, -0.1839,  0.5565],
        [-0.3529,  0.2438, -0.7361],
        [-0.2023,  0.1164,  0.2436],
        [-0.9524, -0.0134,  0.4519]], requires_grad=True)


In [42]:
# 第二种，调用model.parameters()获取不同层的参数
for name, param in net.named_parameters():
    print(name, param)

linear1.weight Parameter containing:
tensor([[-0.6768, -0.1839,  0.5565],
        [-0.3529,  0.2438, -0.7361],
        [-0.2023,  0.1164,  0.2436],
        [-0.9524, -0.0134,  0.4519]], requires_grad=True)
linear1.bias Parameter containing:
tensor([-0.5534,  0.4814,  0.4000,  0.5295], requires_grad=True)
linear2.weight Parameter containing:
tensor([[ 0.1523,  0.5036, -0.0146,  0.1573],
        [-0.4321, -1.3440, -1.5873,  1.5521],
        [ 0.6222, -1.1954, -0.8749, -0.2223],
        [-1.1701, -0.9202, -0.3269, -0.5249]], requires_grad=True)
linear2.bias Parameter containing:
tensor([-0.4008, -0.0533, -0.3891, -0.0154], requires_grad=True)
linear3.weight Parameter containing:
tensor([[ 0.3539,  0.3964,  0.1328, -0.2537],
        [-0.2579,  0.3290, -0.1424,  0.2604]], requires_grad=True)
linear3.bias Parameter containing:
tensor([0.2732, 0.2911], requires_grad=True)


In [43]:
# 第三种，去得到保存参数的dict
d = net.state_dict()
for k, v in d.items():
    print(k, v)

linear1.weight tensor([[-0.6768, -0.1839,  0.5565],
        [-0.3529,  0.2438, -0.7361],
        [-0.2023,  0.1164,  0.2436],
        [-0.9524, -0.0134,  0.4519]])
linear1.bias tensor([-0.5534,  0.4814,  0.4000,  0.5295])
linear2.weight tensor([[ 0.1523,  0.5036, -0.0146,  0.1573],
        [-0.4321, -1.3440, -1.5873,  1.5521],
        [ 0.6222, -1.1954, -0.8749, -0.2223],
        [-1.1701, -0.9202, -0.3269, -0.5249]])
linear2.bias tensor([-0.4008, -0.0533, -0.3891, -0.0154])
linear3.weight tensor([[ 0.3539,  0.3964,  0.1328, -0.2537],
        [-0.2579,  0.3290, -0.1424,  0.2604]])
linear3.bias tensor([0.2732, 0.2911])


In [48]:
# 查看模型结构与参数数量
from torchsummary import summary

summary(net, (3,), batch_size=10, device='cpu')


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [10, 4]              16
            Linear-2                    [10, 4]              20
            Linear-3                    [10, 2]              10
Total params: 46
Trainable params: 46
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [45]:
# device 的设置
net.to('cuda')

MyModel(
  (linear1): Linear(in_features=3, out_features=4, bias=True)
  (linear2): Linear(in_features=4, out_features=4, bias=True)
  (linear3): Linear(in_features=4, out_features=2, bias=True)
)

In [46]:
input = torch.randn(1, 3, 224, 224, device='cuda')
print(input.device)

cuda:0
