In [1]:
# 权重参数初始化
import torch
import torch.nn as nn

In [8]:
linear1 = nn.Linear(5, 2)
# 常数初始化
# 方法一，直接全部置为0 nn.init.zeros_(input)
nn.init.zeros_(linear1.weight)
print(linear1.weight)
# 方法二，可以置为任意常数 nn.init.constant_(input, value)
nn.init.constant_(linear1.weight,0)
print(linear1.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [10]:
# 秩初始化
nn.init.eye_(linear1.weight)
print(linear1.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [13]:
# 正态分布初始化
nn.init.normal_(linear1.weight, mean=0, std=0.01)
print(linear1.weight)

Parameter containing:
tensor([[ 1.0786, -0.4376,  1.2148,  0.8899,  0.5808],
        [ 2.2090, -0.1361,  0.5941,  3.1393,  0.5008]], requires_grad=True)


In [14]:
# 均匀分布初始化
nn.init.uniform_(linear1.weight, -1, 1)

Parameter containing:
tensor([[ 0.4722,  0.8468, -0.4844, -0.2291,  0.5068],
        [-0.0957,  0.7716, -0.6062, -0.0499, -0.9842]], requires_grad=True)

In [16]:
# Xavier 初始化
nn.init.xavier_normal_(linear1.weight)
print(linear1.weight)
nn.init.xavier_uniform_(linear1.weight)
print(linear1.weight)

Parameter containing:
tensor([[ 0.3590,  0.8326,  0.9852, -0.5581,  0.5604],
        [ 0.1483, -0.0219, -0.1648, -0.4267,  0.4566]], requires_grad=True)
Parameter containing:
tensor([[ 0.2505, -0.9245, -0.7518,  0.3972,  0.5516],
        [ 0.1622,  0.5596,  0.0430,  0.6311,  0.1900]], requires_grad=True)


In [18]:
# KaiMing 初始化
nn.init.kaiming_normal_(linear1.weight)
print(linear1.weight)

nn.init.kaiming_uniform_(linear1.weight)
print(linear1.weight)

Parameter containing:
tensor([[ 0.1537,  0.5880, -0.8442, -0.2915,  0.7395],
        [ 1.0480,  0.2945,  0.1856,  0.0909,  0.1759]], requires_grad=True)
Parameter containing:
tensor([[ 0.7928,  0.9159,  0.1377,  0.8861,  0.1134],
        [-0.4204, -0.9458,  0.6456,  0.1420,  0.4757]], requires_grad=True)


In [ ]:
dorpout = nn.Dropout()